#ifndef LOGOS_H
#define LOGOS_H

static const char *logos[][32] = {      // please leave logos[0] to Linux and logos[1] to OSX
    {   // Linux - default logo
        "linux",                                                // this first line contains the distro ID, taken from /etc/os-relase
        "\e[90m",                                               // default color for the printed text
        "                     ",                                // numbers of spaces to use when ran out of logo space
        "\e[90m        #####        ",                          // just the logo
        "\e[90m       #######       ",
        "\e[90m       ##\e[37mO\e[90m#\e[37mO\e[90m##       ",
        "\e[90m       #\e[33m#####\e[90m#       ",
        "\e[90m     ##\e[37m##\e[33m###\e[37m##\e[90m##     ",
        "\e[90m    #\e[37m##########\e[90m##    ",
        "\e[90m   #\e[37m############\e[90m##   ",
        "\e[90m   #\e[37m############\e[90m###  ",
        "\e[33m  ##\e[90m#\e[37m###########\e[90m##\e[33m#  ",
        "\e[33m######\e[90m#\e[37m#######\e[90m#\e[33m######",
        "\e[33m#######\e[90m#\e[37m#####\e[90m#\e[33m#######",
        "\e[33m  #####\e[90m#######\e[33m#####  ",
        ""                                                      // an empty string concludes the logo, to know when it should stop printing
    },
    {   // MacOS X
        "apple",
        "\e[35m",
        "                              ",
        "\e[32m                    'c.       ",
        "\e[32m                 ,xNMM.       ",
        "\e[32m               .OMMMMo        ",
        "\e[32m               OMMM0,         ",
        "\e[32m     .;loddo:' loolloddol;.   ",
        "\e[32m   cKMMMMMMMMMMNWMMMMMMMMMM0: ",
        "\e[33m .KMMMMMMMMMMMMMMMMMMMMMMMWd. ",
        "\e[33m XMMMMMMMMMMMMMMMMMMMMMMMX.   ",
        "\e[31m;MMMMMMMMMMMMMMMMMMMMMMMM:    ",
        "\e[31m:MMMMMMMMMMMMMMMMMMMMMMMM:    ",
        "\e[31m.MMMMMMMMMMMMMMMMMMMMMMMMX.   ",
        "\e[31m kMMMMMMMMMMMMMMMMMMMMMMMMWd. ",
        "\e[35m .XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
        "\e[35m  .XMMMMMMMMMMMMMMMMMMMMMMMMK.",
        "\e[34m    kMMMMMMMMMMMMMMMMMMMMMMd  ",
        "\e[34m     ;KMMMMMMMWXXWMMMMMMMk.   ",
        "\e[34m       .cooc,.    .,coo:.     ",
        ""
    },
    {   // Arch Linux
        "arch",
        "\e[36m",
        "                                     ",
        "\e[36m                   -`                 ",
        "\e[36m                  .o+`                ",
        "\e[36m                 `ooo/                ",
        "\e[36m                `+oooo:               ",
        "\e[36m               `+oooooo:              ",
        "\e[36m               -+oooooo+:             ",
        "\e[36m             `/:-:++oooo+:            ",
        "\e[36m            `/++++/+++++++:           ",
        "\e[36m           `/++++++++++++++:          ",
        "\e[36m          `/+++ooooooooooooo/`        ",
        "\e[36m         ./ooosssso++osssssso+`       ",
        "\e[36m        .oossssso-````/ossssss+`      ",
        "\e[36m       -osssssso.      :ssssssso.     ",
        "\e[36m      :osssssss/        osssso+++.    ",
        "\e[36m     /ossssssss/        +ssssooo/-    ",
        "\e[36m   `/ossssso+/:-        -:/+osssso+-  ",
        "\e[36m  `+sso+:-`                 `.-/+oso: ",
        "\e[36m `++:.                           `-/+/",
        "\e[36m .`                                 `/",
        ""
    },
    {   // Arch Linux (small version)
        "arch_small",
        "\e[36m",
        "\e[36m              ",
        "\e[36m      /\\      ",
        "\e[36m     /  \\     ",
        "\e[36m    /\\   \\    ",
        "\e[36m   /      \\   ",
        "\e[36m  /   ,,   \\  ",
        "\e[36m /   |  |  -\\ ",
        "\e[36m/_-''    ''-_\\",
        ""
    },
    {   // Debian
        "debian",
        "\e[31m",
        "                            ",
        "\e[31m       _,met$$$$$gg.        ",
        "\e[31m    ,g$$$$$$$$$$$$$$$P.     ",
        "\e[31m  ,g$$P\"     \"\"\"Y$$.\".      ",
        "\e[31m ,$$P'              `$$$.   ",
        "\e[31m',$$P       ,ggs.     `$$b: ",
        "\e[31m`d$$'     ,$P\"'   \e[37m.\e[31m    $$$  ",
        "\e[31m $$P      d$'     \e[37m,\e[31m    $$P  ",
        "\e[31m $$:      $$.   \e[37m-\e[31m    ,d$$'  ",
        "\e[31m $$;      Y$b._   _,d$P'    ",
        "\e[31m Y$$.    \e[37m`.\e[31m`\"Y$$$$P\"'       ",
        "\e[31m `$$b      \e[37m\"-.__\e[31m            ",
        "\e[31m  `Y$$                      ",
        "\e[31m   `Y$$.                    ",
        "\e[31m     `$$b.                  ",
        "\e[31m       `Y$$b.               ",
        "\e[31m          `\"Y$b._           ", 
        "\e[31m              `\"\"\"       ",
        ""
    },
    {   // Linux Mint
        "linuxmint",
        "\e[32m",
        "                                        ",
        "\e[37m             ...-:::::-...              ",
        "\e[37m          .-MMMMMMMMMMMMMMM-.           ",
        "\e[37m      .-MMMM\e[32m`..-:::::::-..`\e[37mMMMM-.       ",
        "\e[37m    .:MMMM\e[32m.:MMMMMMMMMMMMMMM:.\e[37mMMMM:.     ",
        "\e[37m   -MMM\e[32m-M---MMMMMMMMMMMMMMMMMMM.\e[37mMMM-    ",
        "\e[37m `:MMM\e[32m:MM`  :MMMM:....::-...-MMMM:\e[37mMMM:` ",
        "\e[37m :MMM\e[32m:MMM`  :MM:`  ``    ``  `:MMM:\e[37mMMM: ",
        "\e[37m.MMM\e[32m.MMMM`  :MM.  -MM.  .MM-  `MMMM.\e[37mMMM.",
        "\e[37m:MMM\e[32m:MMMM`  :MM.  -MM-  .MM:  `MMMM-\e[37mMMM:",
        "\e[37m:MMM\e[32m:MMMM`  :MM.  -MM-  .MM:  `MMMM:\e[37mMMM:",
        "\e[37m:MMM\e[32m:MMMM`  :MM.  -MM-  .MM:  `MMMM-\e[37mMMM:",
        "\e[37m.MMM\e[32m.MMMM`  :MM:--:MM:--:MM:  `MMMM.\e[37mMMM.",
        "\e[37m :MMM\e[32m:MMM-  `-MMMMMMMMMMMM-`  -MMM-\e[37mMMM: ",
        "\e[37m  :MMM\e[32m:MMM:`                `:MMM:\e[37mMMM:  ",
        "\e[37m   .MMM\e[32m.MMMM:--------------:MMMM.\e[37mMMM.   ",
        "\e[37m     '-MMMM\e[32m.-MMMMMMMMMMMMMMM-.\e[37mMMMM-'    ",
        "\e[37m       '.-MMMM\e[32m``--:::::--``\e[37mMMMM-.'      ",
        "\e[37m            '-MMMMMMMMMMMMM-'           ",
        "\e[37m               ``-:::::-``              ",
        ""
    },
    {   // Endeavour OS
        "endeavouros",
        "\e[35m",
        "                                        ",
        "\e[31m                     ./\e[35mo\e[34m.               ",
        "\e[31m                   ./\e[35msssso\e[34m-             ",
        "\e[31m                 `:\e[35mosssssss+\e[34m-           ",
        "\e[31m               `:+\e[35msssssssssso\e[34m/.         ",
        "\e[31m             `-/o\e[35mssssssssssssso\e[34m/.       ",
        "\e[31m           `-/+\e[35msssssssssssssssso\e[34m+:`     ",
        "\e[31m         `-:/+\e[35msssssssssssssssssso«\e[34m+/.   ",
        "\e[31m       `.://\e[35mosssssssssssssssssssso\e[34m++-   ",
        "\e[31m      .://+\e[35mssssssssssssssssssssssso\e[34m++:  ",
        "\e[31m    .:///\e[35mossssssssssssssssssssssssso\e[34m++: ",
        "\e[31m  `:////\e[35mssssssssssssssssssssssssssso\e[34m+++.",
        "\e[31m`-////+\e[35mssssssssssssssssssssssssssso\e[34m++++-",
        "\e[31m `..-+\e[35moosssssssssssssssssssssssso\e[34m+++++/`",
        "\e[34m   ./++++++++++++++++++++++++++++++/:.  ",
        "\e[34m  `:::::::::::::::::::::::::------``    ",
        ""
    },
    {   // Ubuntu
        "ubuntu",
        "\e[31m",
        "                                        ",
        "\e[31m            .-/+oossssoo+/-.            ",
        "\e[31m        `:+ssssssssssssssssss+:`        ",
        "\e[31m      -+ssssssssssssssssssyyssss+-      ",
        "\e[31m    .ossssssssssssssssss\e[37mdMMMNy\e[31msssso.    ",
        "\e[31m   /sssssssssss\e[37mhdmmNNmmyNMMMMh\e[31mssssss/   ",
        "\e[31m  +sssssssss\e[37mhm\e[31myd\e[37mMMMMMMMNddddy\e[31mssssssss+  ",
        "\e[31m /ssssssss\e[37mhNMMM\e[31myh\e[37mhyyyyhmNMMMNh\e[31mssssssss/ ",
        "\e[31m.ssssssss\e[37mdMMMNh\e[31mssssssssss\e[37mhNMMMd\e[31mssssssss.",
        "\e[31m+ssss\e[37mhhhyNMMNy\e[31mssssssssssss\e[37myNMMMy\e[31msssssss+",
        "\e[31moss\e[37myNMMMNyMMh\e[31mssssssssssssss\e[37mhmmmh\e[31mssssssso",
        "\e[31moss\e[37myNMMMNyMMh\e[31msssssssssssssshmmmhssssssso",
        "\e[31m+ssss\e[37mhhhyNMMNy\e[31mssssssssssss\e[37myNMMMy\e[31msssssss+",
        "\e[31m.ssssssss\e[37mdMMMNh\e[31mssssssssss\e[37mhNMMMd\e[31mssssssss.",
        "\e[31m /ssssssss\e[37mhNMMM\e[31myh\e[37mhyyyyhdNMMMNh\e[31mssssssss/ ",
        "\e[31m  +sssssssss\e[37mdm\e[31myd\e[37mMMMMMMMMddddy\e[31mssssssss+  ",
        "\e[31m   /sssssssssss\e[37mhdmNNNNmyNMMMMh\e[31mssssss/   ",
        "\e[31m    .ossssssssssssssssss\e[37mdMMMNy\e[31msssso.    ",
        "\e[31m      -+sssssssssssssssss\e[37myyy\e[31mssss+-      ",
        "\e[31m        `:+ssssssssssssssssss+:`        ",
        "\e[31m            .-/+oossssoo+/-.            ",
        ""
    },
    {   // Parrot OS
        "parrot",
        "\e[36m",
        "                                       ",
        "\e[36m  `:oho/-`                             ",
        "\e[36m`mMMMMMMMMMMMNmmdhy-                   ",
        "\e[36m dMMMMMMMMMMMMMMMMMMs`                 ",
        "\e[36m +MMsohNMMMMMMMMMMMMMm/                ",
        "\e[36m .My   .+dMMMMMMMMMMMMMh.              ",
        "\e[36m  +       :NMMMMMMMMMMMMNo             ",
        "\e[36m           `yMMMMMMMMMMMMMm:           ",
        "\e[36m             /NMMMMMMMMMMMMMy`         ",
        "\e[36m              .hMMMMMMMMMMMMMN+        ",
        "\e[36m                  ``-NMMMMMMMMMd-      ",
        "\e[36m                     /MMMMMMMMMMMs`    ",
        "\e[36m                      mMMMMMMMsyNMN/   ",
        "\e[36m                      +MMMMMMMo  :sNh. ",
        "\e[36m                      `NMMMMMMm     -o/",
        "\e[36m                       oMMMMMMM.       ",
        "\e[36m                       `NMMMMMM+       ",
        "\e[36m                        +MMd/NMh       ",
        "\e[36m                         mMm -mN`      ",
        "\e[36m                         /MM  `h:      ",
        "\e[36m                          dM`   .      ",
        "\e[36m                          :M-          ",
        "\e[36m                           d:          ",
        "\e[36m                           -+          ",
        "\e[36m                            -          ",
        ""
    },
    {   // Manjaro Linux
        "manjaro",
        "\e[32m",
        "                            ",
        "\e[32m██████████████████  ████████",
        "\e[32m██████████████████  ████████",
        "\e[32m██████████████████  ████████",
        "\e[32m██████████████████  ████████",
        "\e[32m████████            ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        "\e[32m████████  ████████  ████████",
        ""
    },
    {   // Fedora
        "fedora",
        "\e[34m",
        "                                  ",
        "\e[34m          /:-------------:\\       ",
        "\e[34m       :-------------------::     ",
        "\e[34m     :-----------\e[39m/shhOHbmp\e[34m---:\\   ",
        "\e[34m   /-----------\e[39momMMMNNNMMD\e[34m]  ---:  ",
        "\e[34m  :-----------\e[39msMMMMNMNMP\e[34m.    ---: ",
        "\e[34m :-----------\e[39m:MMMdP\e[34m-------    ---\\",
        "\e[34m,------------\e[39m:MMMd\e[34m--------    ---:",
        "\e[34m:------------\e[39m:MMMd\e[34m-------    .---:",
        "\e[34m:----    \e[39moNMMMMMMMMMNho\e[34m     .----:",
        "\e[34m:--     .\e[39m+shhhMMMmhhy++\e[34m   .------/",
        "\e[34m:-    -------\e[39m:MMMd\e[34m--------------: ",
        "\e[34m:-   --------\e[39m/MMMd\e[34m-------------;  ",
        "\e[34m:-    ------\e[39m/hMMMy\e[34m------------:   ",
        "\e[34m:-- \e[39m:dMNdhhdNMMNo\e[34m------------;    ",
        "\e[34m:---\e[39m:sdNMMMMNds:\e[34m------------:     ",
        "\e[34m:------\e[39m:://:\e[34m-------------::       ",
        "\e[34m:---------------------://         ",
        ""
    },
    {   // KDE Neon
        "neon",
        "\e[32m",
        "                                        ",
        "\e[32m             `..---+/---..`             ",
        "\e[32m         `---.``   ``   `.---.`         ",
        "\e[32m      .--.`        ``        `-:-.      ",
        "\e[32m    `:/:     `.----//----.`     :/-     ",
        "\e[32m   .:.    `---`          `--.`    .:`   ",
        "\e[32m  .:`   `--`                .:-    `:.  ",
        "\e[32m `/    `:.      `.-::-.`      -:`   `/` ",
        "\e[32m /.    /.     `:++++++++:`     .:    .: ",
        "\e[32m`/    .:     `+++++++++++/      /`   `+`",
        "\e[32m/+`   --     .++++++++++++`     :.   .+:",
        "\e[32m`/    .:     `+++++++++++/      /`   `+`",
        "\e[32m /`    /.     `:++++++++:`     .:    .: ",
        "\e[32m ./    `:.      `.:::-.`      -:`   `/` ",
        "\e[32m  .:`   `--`                .:-    `:.  ",
        "\e[32m   .:.    `---`          `--.`    .:`   ",
        "\e[32m    `:/:     `.----//----.`     :/-     ",
        "\e[32m      .-:.`        ``        `-:-.      ",
        "\e[32m         `---.``   ``   `.---.`         ",
        "\e[32m             `..---+/---..`             ",
        ""
    },
    {   // Pop!_OS
        "pop",
        "\e[36m",
        "                                       ",
        "\e[36m             /////////////             ",
        "\e[36m         /////////////////////         ",
        "\e[36m      ///////\e[39m*767\e[36m////////////////      ",
        "\e[36m    //////\e[39m7676767676*\e[36m//////////////    ",
        "\e[36m   /////\e[39m76767\e[36m//\e[39m7676767\e[36m//////////////   ",
        "\e[36m  /////\e[39m767676\e[36m///\e[39m*76767\e[36m///////////////  ",
        "\e[36m ///////\e[39m767676\e[36m///\e[39m76767\e[36m].///\e[39m7676*\e[36m///////",
        "\e[36m/////////\e[39m767676\e[36m//\e[39m76767\e[36m///\e[39m767676\e[36m////////",
        "\e[36m//////////\e[39m76767676767\e[36m////\e[39m76767\e[36m/////////",
        "\e[36m///////////\e[39m76767676\e[36m//////\e[39m7676\e[36m//////////",
        "\e[36m////////////,\e[39m7676\e[36m,///////\e[39m767\e[36m///////////",
        "\e[36m/////////////*\e[39m7676\e[36m///////\e[39m76\e[36m////////////",
        "\e[36m///////////////\e[39m7676\e[36m////////////////////",
        "\e[36m ///////////////\e[39m7676\e[36m///\e[39m767\e[36m//////////// ",
        "\e[36m  //////////////////////\e[39m'\e[36m////////////  ",
        "\e[36m   //////\e[39m.7676767676767676767,\e[36m//////   ",
        "\e[36m    /////\e[39m767676767676767676767\e[36m/////    ",
        "\e[36m      ///////////////////////////      ",
        "\e[36m         /////////////////////         ",
        "\e[36m             /////////////             ",
        ""
    },
    {   // Gentoo
        "gentoo",
        "\e[35m",
        "                                ",
        "\e[35m         -/oyddmdhs+:.             ",
        "\e[35m    -o\e[37mdNMMMMMMMMNNmhy+\e[35m-`          ",
        "\e[35m   -y\e[37mNMMMMMMMMMMMNNNmmdhy\e[35m+-        ",
        "\e[35m `o\e[37mmMMMMMMMMMMMMNmdmmmmddhhy\e[35m/`     ",
        "\e[35m om\e[37mMMMMMMMMMMMN\e[35mhhyyyo\e[37mhmdddhhhd\e[35mo`   ",
        "\e[35m.y\e[37mdMMMMMMMMMMd\e[35mhs++so/s\e[37mmdddhhhhdm\e[35m+` ",
        "\e[35m oy\e[37mhdmNMMMMMMMN\e[35mdyooy\e[37mdmddddhhhhyhN\e[35md.",
        "\e[35m  :o\e[37myhhdNNMMMMMMMNNNmmdddhhhhhyym\e[35mMh",
        "\e[35m    .:\e[37m+sydNMMMMMNNNmmmdddhhhhhhmM\e[35mmy",
        "\e[35m       /m\e[37mMMMMMMNNNmmmdddhhhhhmMNh\e[35ms:",
        "\e[35m    `o\e[37mNMMMMMMMNNNmmmddddhhdmMNhs\e[35m+` ",
        "\e[35m  `s\e[37mNMMMMMMMMNNNmmmdddddmNMmhs\e[35m/.   ",
        "\e[35m /N\e[37mMMMMMMMMNNNNmmmdddmNMNdso\e[35m:`     ",
        "\e[35m+M\e[37mMMMMMMNNNNNmmmmdmNMNdso\e[35m/-        ",
        "\e[35myM\e[37mMNNNNNNNmmmmmNNMmhs+/\e[35m-`          ",
        "\e[35m/h\e[37mMMNNNNNNNNMNdhs++/\e[35m-`             ",
        "\e[35m `/\e[37mohdmmddhys+++/:\e[35m.`               ",
        "\e[35m  `-//////:--.                      ",
        ""
    },
    {   // Windows
        "windows",
        "\e[34m",
        "                                     ",
        "\e[31m        ,.=:!!t3Z3z.,                ",
        "\e[31m       :tt:::tt333EE3                ",
        "\e[31m       Et:::ztt33EEEL \e[32m@Ee.,      .., ",
        "\e[31m      ;tt:::tt333EE7 \e[32m;EEEEEEttttt33# ",
        "\e[31m     :Et:::zt333EEQ. \e[32m$EEEEEttttt33QL ",
        "\e[31m     it::::tt333EEF \e[32m@EEEEEEttttt33F  ",
        "\e[31m    ;3=*^```\"*4EEV \e[32m:EEEEEEttttt33@.  ",
        "\e[34m    ,.=::::!t=., \e[31m` \e[32m@EEEEEEtttz33QF   ",
        "\e[34m   ;::::::::zt33)   \e[32m\"4EEEtttji3P*    ",
        "\e[34m  :t::::::::tt33.\e[33m:Z3z..  \e[32m`` \e[33m,..g.    ",
        "\e[34m  i::::::::zt33F \e[33mAEEEtttt::::ztF     ",
        "\e[34m ;:::::::::t33V \e[33m;EEEttttt::::t3      ",
        "\e[34m E::::::::zt33L \e[33m@EEEtttt::::z3F      ",
        "\e[34m{3=*^```\"*4E3) \e[33m;EEEtttt:::::tZ`      ",
        "\e[34m             `\e[33m \e[33m:EEEEtttt::::z7       ",
        "\e[33m                 \"VEzjt:;;z>*`       ",
        ""
    },
    {   // ElementaryOS
        "elementary",
        "\e[34m",
        "                                    ",
        "\e[0m         eeeeeeeeeeeeeeeee          ",
        "\e[37m      eeeeeeeeeeeeeeeeeeeeeee       ",
        "\e[37m    eeeee  eeeeeeeeeeee   eeeee     ",
        "\e[37m  eeee   eeeee       eee     eeee   ",
        "\e[37m eeee   eeee          eee     eeee  ",
        "\e[37meee    eee            eee       eee ",
        "\e[37meee   eee            eee        eee ",
        "\e[37mee    eee           eeee       eeee ",
        "\e[37mee    eee         eeeee      eeeeee ",
        "\e[37mee    eee       eeeee      eeeee ee ",
        "\e[37meee   eeee   eeeeee      eeeee  eee ",
        "\e[37meee    eeeeeeeeee     eeeeee    eee ",
        "\e[37m eeeeeeeeeeeeeeeeeeeeeeee    eeeee  ",
        "\e[37m  eeeeeeee eeeeeeeeeeee      eeee   ",
        "\e[37m    eeeee                 eeeee     ",
        "\e[37m      eeeeeee         eeeeeee       ",
        "\e[37m         eeeeeeeeeeeeeeeee          ",
        ""
    },
};

#endif
